//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UBand.WEB.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seguimiento
    {
        public int SeguimientoId { get; set; }
        public int UsuarioId { get; set; }
        public Nullable<int> BandaId { get; set; }
        public Nullable<int> UsuarioSeguirId { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public bool Sigue { get; set; }
    
        public virtual Banda Banda { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
