//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UBand.WEB.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioBanda
    {
        public int UsuarioBandaId { get; set; }
        public int UsuarioId { get; set; }
        public int BandaId { get; set; }
        public string Rol { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public Nullable<System.DateTime> FechaEgreso { get; set; }
        public string Estado { get; set; }
    
        public virtual Banda Banda { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
