//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FACEBAND.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Actividad
    {
        public int ActividadId { get; set; }
        public string Titulo { get; set; }
        public string Descripción { get; set; }
        public Nullable<int> UsuEmisorId { get; set; }
        public Nullable<int> UsuDestinatarioId { get; set; }
        public Nullable<int> BandaDestinatarioId { get; set; }
        public Nullable<int> BandaEmisorId { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Estado { get; set; }
    
        public virtual Banda Banda { get; set; }
        public virtual Banda Banda1 { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
