//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FACEBAND.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banda
    {
        public Banda()
        {
            this.Actividad = new HashSet<Actividad>();
            this.Actividad1 = new HashSet<Actividad>();
            this.GeneroBanda = new HashSet<GeneroBanda>();
            this.MensajeBanda = new HashSet<MensajeBanda>();
            this.Seguimiento = new HashSet<Seguimiento>();
            this.UsuarioBanda = new HashSet<UsuarioBanda>();
        }
    
        public int BandaId { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Foto { get; set; }
        public string Ubicacion { get; set; }
        public Nullable<int> Seguidores { get; set; }
        public string Estado { get; set; }
    
        public virtual ICollection<Actividad> Actividad { get; set; }
        public virtual ICollection<Actividad> Actividad1 { get; set; }
        public virtual ICollection<GeneroBanda> GeneroBanda { get; set; }
        public virtual ICollection<MensajeBanda> MensajeBanda { get; set; }
        public virtual ICollection<Seguimiento> Seguimiento { get; set; }
        public virtual ICollection<UsuarioBanda> UsuarioBanda { get; set; }
    }
}
