//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FACEBAND.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneroBanda
    {
        public int GeneroBandaId { get; set; }
        public int BandaId { get; set; }
        public int GeneroId { get; set; }
        public string Estado { get; set; }
    
        public virtual Banda Banda { get; set; }
        public virtual Genero Genero { get; set; }
    }
}
