//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FACEBAND.WEB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FaceBandEntities : DbContext
    {
        public FaceBandEntities()
            : base("name=FaceBandEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Actividad> Actividad { get; set; }
        public DbSet<Banda> Banda { get; set; }
        public DbSet<Genero> Genero { get; set; }
        public DbSet<GeneroBanda> GeneroBanda { get; set; }
        public DbSet<MensajeBanda> MensajeBanda { get; set; }
        public DbSet<Seguimiento> Seguimiento { get; set; }
        public DbSet<Token> Token { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
        public DbSet<UsuarioBanda> UsuarioBanda { get; set; }
    }
}
