//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FACEBAND.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Token
    {
        public Token()
        {
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int TokenId { get; set; }
        public string Codigo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaExpiracion { get; set; }
    
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
