//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FACEBAND.WEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Actividad = new HashSet<Actividad>();
            this.Actividad1 = new HashSet<Actividad>();
            this.MensajeBanda = new HashSet<MensajeBanda>();
            this.Seguimiento = new HashSet<Seguimiento>();
            this.Seguimiento1 = new HashSet<Seguimiento>();
            this.UsuarioBanda = new HashSet<UsuarioBanda>();
        }
    
        public int UsuarioId { get; set; }
        public string Codigo { get; set; }
        public string Password { get; set; }
        public string Salt { get; set; }
        public string Nombres { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Foto { get; set; }
        public Nullable<int> TokenId { get; set; }
        public string Rol { get; set; }
        public string Estado { get; set; }
    
        public virtual ICollection<Actividad> Actividad { get; set; }
        public virtual ICollection<Actividad> Actividad1 { get; set; }
        public virtual ICollection<MensajeBanda> MensajeBanda { get; set; }
        public virtual ICollection<Seguimiento> Seguimiento { get; set; }
        public virtual ICollection<Seguimiento> Seguimiento1 { get; set; }
        public virtual Token Token { get; set; }
        public virtual ICollection<UsuarioBanda> UsuarioBanda { get; set; }
    }
}
