//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FACEBAND.WEB.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MensajeBanda
    {
        public int BandaMensajeId { get; set; }
        public int UsuarioId { get; set; }
        public int BandaId { get; set; }
        public string Mensaje { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Estado { get; set; }
    
        public virtual Banda Banda { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
