//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FACEBAND.WEB.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        public int SolicitudId { get; set; }
        public string Titulo { get; set; }
        public string Texto { get; set; }
        public Nullable<int> UsuarioEmisorId { get; set; }
        public Nullable<int> UsuarioReceptorId { get; set; }
        public Nullable<int> BandaEmisoraId { get; set; }
        public Nullable<int> BandaReceptoraId { get; set; }
        public string Estado { get; set; }
    
        public virtual Banda Banda { get; set; }
        public virtual Banda Banda1 { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
